dist: xenial

matrix:
    include:
        - language: python
          python: "3.6"
          os: linux
        - language: python
          python: "3.7"
          os: linux
        - language: python
          python: "3.8-dev"
          os: linux
        - os: windows
          language: sh
    allow_failures:
        - os: windows
          language: sh
    fast_finish: true

cache:
    pip: true
    directories:
        - $HOME/eyeD3-test-data

before_install:
  - >
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install python3
      ln -s $(which py) /usr/bin/python3
    fi

install:
    - pip install -U -r requirements.txt
    - pip install -U -r requirements/test.txt
    - pip install coveralls
    - pip install -e .
    - make TEST_DATA_DIR=$HOME test-data

# command to run tests
script: make coverage

after_success:
  - coveralls
